name: Build project
on:
  push:
    branches:
      - master
    paths:
      - ".github/**"
      - "src/**"
      - "build.gradle"
      - "gradle.properties"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "17"
          cache: "gradle"

      - name: Build and Test
        run: ./gradlew clean build jacocoTestReport

      - name: Upload coverage to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
