name: Build project
on:
  push:
    branches:
      - master
    paths:
      - ".github/**"
      - "src/**"
      - "log-masking-lib/src/**"
      - "log-masking-lib/build.gradle"
      - "build.gradle"
      - "gradle.properties"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "17"
          cache: "gradle"

      - name: Build and Test
        run: ./gradlew clean build

      - name: Upload coverage to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Publish images
        run: |
          docker compose build
          docker compose push
